// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact_privacy.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const listContactVisibleUserIDs = `-- name: ListContactVisibleUserIDs :many
WITH viewer_rides AS (
    SELECT id AS ride_id FROM rides WHERE owner_id = $2
    UNION
    SELECT ride_id FROM ride_occupants WHERE user_id = $2
)
SELECT u.id
FROM users u
WHERE u.id = ANY($1::uuid[])
  AND (
      u.id = $2
      OR EXISTS (
          SELECT 1
          FROM viewer_rides vr
          JOIN rides r ON r.id = vr.ride_id
          WHERE r.owner_id = u.id
             OR EXISTS (
                 SELECT 1 FROM ride_occupants target_ro
                 WHERE target_ro.ride_id = vr.ride_id AND target_ro.user_id = u.id
             )
      )
  )
`

type ListContactVisibleUserIDsParams struct {
	TargetIds []uuid.UUID `json:"target_ids"`
	ViewerID  uuid.UUID   `json:"viewer_id"`
}

// ListContactVisibleUserIDs returns target IDs whose contacts the viewer may see. A shared ride
// counts even when it is in the past or cancelled; self is always visible.
// Fetch all matches in one query so ride lists do not query once per rider.
func (q *Queries) ListContactVisibleUserIDs(ctx context.Context, arg ListContactVisibleUserIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listContactVisibleUserIDs, pq.Array(arg.TargetIds), arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
