// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type RideStatus string

const (
	RideStatusActive    RideStatus = "active"
	RideStatusCancelled RideStatus = "cancelled"
)

func (e *RideStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RideStatus(s)
	case string:
		*e = RideStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RideStatus: %T", src)
	}
	return nil
}

type NullRideStatus struct {
	RideStatus RideStatus `json:"ride_status"`
	Valid      bool       `json:"valid"` // Valid is true if RideStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRideStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RideStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RideStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRideStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RideStatus), nil
}

type Location struct {
	ID      uuid.UUID `json:"id"`
	Title   string    `json:"title"`
	Address string    `json:"address"`
}

type Ride struct {
	ID                  uuid.UUID  `json:"id"`
	DepartureTime       time.Time  `json:"departure_time"`
	DepartureLocationID uuid.UUID  `json:"departure_location_id"`
	ArrivalLocationID   uuid.UUID  `json:"arrival_location_id"`
	OwnerID             uuid.UUID  `json:"owner_id"`
	Notes               string     `json:"notes"`
	Capacity            int32      `json:"capacity"`
	Status              RideStatus `json:"status"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
}

type RideOccupant struct {
	RideID   uuid.UUID `json:"ride_id"`
	UserID   uuid.UUID `json:"user_id"`
	JoinedAt time.Time `json:"joined_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
	Phone     string    `json:"phone"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
